services:
  gcp_django:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - framework/mysite:/mysite
    ports:
      - 8881:8881
    entrypoint:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8881