version: '3.3'
services:
  gcpdjango:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../mysite:/mysite
    ports:
      - 8881:8881
    command: python